### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by CookieGuy123** [PlanetTheCloud/project-logged#17]
So I installed and configured this on MyOwnFreeHost, and it worked correctly! 😄 

BUT

I installed [MOFH Material Template](https://github.com/MOFHDevs/mofh-material-template) and now it says

**Fatal error: Uncaught TypeError: Argument 1 passed to Arr::dot() must be of the type array, null given, called in /home/vol12_1/fastfreehost.ml/www/htdocs/sys-auth/app/app.php on line 18 and defined in /home/vol12_1/fastfreehost.ml/www/htdocs/sys-auth/app/arr.class.php:25 Stack trace: #0 /home/vol12_1/fastfreehost.ml/www/htdocs/sys-auth/app/app.php(18): Arr::dot(NULL) #1 /home/vol12_1/fastfreehost.ml/www/htdocs/signup.php(12): require('/home/vol12_1/f...') #2 {main} thrown in /home/vol12_1/fastfreehost.ml/www/htdocs/sys-auth/app/arr.class.php on line 25**

It was working fine before, but it says this AFTER I installed the theme... but the theme didn't have 'signup.php' in the files that you need to upload. 

What should I do?

**Comment by nabeelshaikh7** [comment]
The "Theme"  you installed is not actually a theme . It's a signup software like project logged and it is not compatible with project logged .

**Comment by CookieGuy123** [comment]
Oh. ok

**Comment by aa22dev** [comment]
There moght be some conflicts between both, and that is just a template not a signup theme like project logged.

Open an issue there for compatibility checks @4yx and I will look into it.

There is nothing wrong with project logged.

**Comment by PlanetTheCloud** [comment]
Hi, It looks like there's some sort of conflict going on. But can you try reinstalling LOGGED on top of it and see if that works?

**Comment by PlanetTheCloud** [comment]
Hi there, I'm still waiting for your response. Kindly reopen this issue if needed. Thanks.

**Comment by 4yx** [comment]
> The "Theme" you installed is not actually a theme . It's a signup software like project logged and it is not compatible with project logged .

Huh? I'm pretty sure it's a theme/template. We don't have a default signup page though I'll probably make one.
It was meant to be compatible/working alongside Project LOGGED.

> It was working fine before, but it says this AFTER I installed the theme... but the theme didn't have 'signup.php' in the files that you need to upload.

I'll try installing it now myself and see if it causes any issues.

**Comment by 4yx** [comment]
@mahofficial and I were able to determine why it breaks, and a solution is being worked on. 
~~We will include a temporary fix on our end until this can be fixed on LOGGED's side.~~

Issue fixed by @mahofficial in https://github.com/PlanetTheCloud/project-logged/commit/4e8aab24e90608a185f23cb8d1c8c20389102342.

**Comment by PlanetTheCloud** [comment]
Thank you for resolving the error.

**Comment by aa22dev** [comment]
> @mahofficial and I were able to determine why it breaks, and a solution is being worked on.
> We will include a temporary fix on our end until this can be fixed on LOGGED's side.
> 
> You can download the new version on https://github.com/MOFHDevs/mofh-material-template/tree/logged-temp, make sure you remove the old files first, especially our config.php.

It's fixed now with new commit, I believe.

**Comment by 4yx** [comment]
> @mahofficial said:
> > @4yx said:
> > @mahofficial and I were able to determine why it breaks, and a solution is being worked on.
> > We will include a temporary fix on our end until this can be fixed on LOGGED's side.
> > You can download the new version on [https://github.com/MOFHDevs/mofh-material-template/tree/logged-temp](https://github.com/MOFHDevs/mofh-material-template/tree/logged-temp?rgh-link-date=2021-06-26T05%3A16%3A31Z), make sure you remove the old files first, especially our config.php.
> 
> It's fixed now with new commit, I believe.

Awesome, @CookieGuy123 could you verify if installing the new version of LOGGED (with the normal template files you have, not the link I posted yesterday) works?
