### ISSUE TITLE
feature request: use subdomain to find username

### ISSUE THREAD

**Issue by zeroninefourfour** [PlanetTheCloud/project-logged#18]
on login panel.i think you can use  https://github.com/InfinityFreeHosting/mofh-client  GetUserDomains.i think that will make customer better to login

**Comment by Sarveshmrao** [comment]
The mofh-client by HansAdema (InfinityFreeHosting) is an client for the MOFH API. But Project Logged is just a sign up page and doesn't have client area and doesn't use the MOFH API.

**Comment by PlanetTheCloud** [comment]
Hi, can you please elaborate on how will it make customer's login better? I would love to do that

**Comment by PlanetTheCloud** [comment]
Hi there, I'm still waiting for your response. Kindly reopen this issue if needed. Thanks.
