### ISSUE TITLE
Multi domain select on signup

### ISSUE THREAD

**Issue by OutragedMetro** [PlanetTheCloud/project-logged#23]
I am using the multidomain select on signup got this installed on both but am running into the following error on signup

`Something went wrong. Please try again.`

**Comment by PlanetTheCloud** [comment]
Hi, please enable debug mode and attach the debug message here. Thank you.

**Comment by OutragedMetro** [comment]
Hello so this is the debug message I currently recieve
`Project LOGGED: Debug Mode.
Something went wrong. Please try again.array(1) { [0]=> array(3) { ["file"]=> string(63) "/home/vol2_1/gateway-hosting.com/www/o-m.club/htdocs/signup.php" ["line"]=> int(137) ["function"]=> string(6) "reject" } } `

**Comment by OutragedMetro** [comment]
Problem Solved

**Comment by ash3T** [comment]
Thanks for developing this code.
