### ISSUE TITLE
Potential issues with domain_name field

### ISSUE THREAD

**Issue by PlanetTheCloud** [PlanetTheCloud/project-logged#26]
As reported by BastelPichi, this field may cause the reseller account to get banned.

**Comment by PlanetTheCloud** [comment]
Support ticket created. Waiting for response.

**Comment by BastelPichi** [comment]
Any Updates yet?

**Comment by PlanetTheCloud** [comment]
Yes there's reply and we're having a conversation

**Comment by PlanetTheCloud** [comment]
Conversation with iFastNet support has concluded. The result is that: No, reseller won't be suspended. It is not the responsibility of the reseller for the domains added by clients.

**Comment by BastelPichi** [comment]
Well, aj.do is suspended after all... 
I'll try to Talk to them about this.
