### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by xiaoioi** [PlanetTheCloud/project-logged#28]
Chinese Translation

Most of them are machine translated.

zh-hans.json is simplified Chinese
zh-hant.json is Traditional Chinese
[Chinese.zip](https://github.com/PlanetTheCloud/project-logged/files/11857436/Chinese.zip)

This content is also machine translated, laugh :)

**Comment by PlanetTheCloud** [comment]
Hi, no worries if it's machine translated, as long as you understand Chinese and it is correct, you can open a pull request.
