### ISSUE TITLE
cPanel URL option does not really works yet..

### ISSUE THREAD

**Issue by PlanetTheCloud** [PlanetTheCloud/project-logged#3]
The cPanel URL option does work for Logins but it does not work for signups since you need to be on the target site `ROOT/signup.php` domain in order to do that.  
Plan for this (Able to communicate with remote sites) was submitted for Project LOGGED 1.7.  

Recomendations : Drop support for cPanel URL for signup.

**Comment by aa22dev** [comment]
@PlanetGamingGG How about sending request to a file hosted on the target site from signup page

**Comment by PlanetTheCloud** [comment]
Hi, as stated above, plan for this was submitted to LOGGED 1.7.
1.6 will not have this feature.

If you wish, you can add your own code for this on signup.php file.

**Comment by aa22dev** [comment]
okay!

**Comment by PlanetTheCloud** [comment]
This has been fixed.
