### ISSUE TITLE
domain_name functionality removed

### ISSUE THREAD

**Issue by BastelPichi** [PlanetTheCloud/project-logged#36]
After an bug report by an community member, the domain_name field has been removed for security reasons. So this wont work anymore.

Ive contacted iFastNet about this.

**Comment by BastelPichi** [comment]
![grafik](https://github.com/PlanetTheCloud/project-logged/assets/63782569/db549a9f-d874-45b8-8576-b8534a96b407)

**Comment by PlanetTheCloud** [comment]
I see, I'd like to go into details with the bug mentioned above. Kindly let me know the details on my Discord DM. Thanks.
